### ISSUE TITLE
Completed

### ISSUE THREAD

**Issue by itskoi** [itskoi/P4DS-FinalProject#3]
Our team has completed this project. We look forward to hearing your comments 😄 Please feel free to comment on how we can improve this project, thanks in advance!

**Comment by thnam4500** [comment]
Cá nhân mình thấy project có bố cục ổn, có phân chia đủ các phần, có giải thích đầy đủ những lợi ích khi trả lời các câu hỏi tự đặt ra, có preprocess để xử lý những vị trí dữ liệu có vấn đề, dẫn dắt giải thích trực quan hoá tốt nên mình không có ý kiến gì thêm về đồ án

**Comment by baminh2203** [comment]
Mình thấy đồ án của nhóm rất có đầu tư, đầy đủ rõ ràng, các câu hỏi hay nhưng mình nghĩ các bước tiền xử lí có phần hơi dài xíu.
Còn lại mình thấy rất hay nên không có ý kiến gì thêm

**Comment by itskoi** [comment]
Everything done!
